name: Generate MonkeyType README SVG

on:
  schedule:
    - cron: "0 */6 * * *"    # runs every 6 hours
  workflow_dispatch:

jobs:
  download-svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Generate MonkeyType SVG
        uses: monkeytype-hub/monkeytype-readme@v1.0.0
        with:
          username: KrakenAspecto
          themes: gruvbox_dark   # e.g. "nord_light" (replace spaces with underscores)
          target-branch: monkeytype-readme
          github-token: ${{ secrets.GITHUB_TOKEN }}

